# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(db_index=True, max_length=180)),
                ('pop', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UK_locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=20)),
                ('place_name', models.CharField(db_index=True, max_length=180)),
                ('admin_name1', models.CharField(max_length=100)),
                ('admin_code1', models.CharField(max_length=20)),
                ('admin_name2', models.CharField(max_length=100)),
                ('admin_code2', models.CharField(max_length=20)),
                ('admin_name3', models.CharField(max_length=100)),
                ('admin_code3', models.CharField(max_length=20)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.IntegerField()),
            ],
        ),
    ]
