# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='uk_location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('postal_code', models.CharField(max_length=20)),
                ('place_name', models.CharField(db_index=True, max_length=180)),
                ('admin_name1', models.CharField(max_length=100, null=True)),
                ('admin_code1', models.CharField(max_length=20, null=True)),
                ('admin_name2', models.CharField(max_length=100, null=True)),
                ('admin_code2', models.CharField(max_length=20, null=True)),
                ('admin_name3', models.CharField(max_length=100, null=True)),
                ('admin_code3', models.CharField(max_length=20, null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('accuracy', models.IntegerField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='UK_locations',
        ),
    ]
