# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 15:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveltime', '0003_population_region_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='uk_location',
            name='pop_entry',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='traveltime.Population'),
        ),
    ]
