# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 16:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveltime', '0004_uk_location_pop_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uk_location',
            name='id',
        ),
        migrations.AlterField(
            model_name='uk_location',
            name='place_name',
            field=models.CharField(max_length=180, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='uk_location',
            name='pop_entry',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location', to='traveltime.Population'),
        ),
    ]
