# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 16:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveltime', '0005_auto_20161119_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uk_location',
            name='pop_entry',
        ),
        migrations.AddField(
            model_name='population',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pop_entry', to='traveltime.uk_location'),
        ),
    ]
