# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 17:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveltime', '0007_distancematrix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distancematrix',
            name='place1',
        ),
        migrations.RemoveField(
            model_name='distancematrix',
            name='place2',
        ),
        migrations.AddField(
            model_name='uk_location',
            name='route_ends',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place2', to='traveltime.DistanceMatrix'),
        ),
        migrations.AddField(
            model_name='uk_location',
            name='route_starts',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place1', to='traveltime.DistanceMatrix'),
        ),
    ]
