# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltime', '0009_auto_20161119_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='id',
            field=models.AutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='population',
            name='place_name',
            field=models.CharField(db_index=True, max_length=180),
        ),
    ]
