# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveltime', '0011_auto_20161119_1841'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='largetown',
            name='route_ends',
        ),
        migrations.RemoveField(
            model_name='largetown',
            name='route_starts',
        ),
        migrations.AddField(
            model_name='distancematrix',
            name='end',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_end', to='traveltime.LargeTown'),
        ),
        migrations.AddField(
            model_name='distancematrix',
            name='start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='route_start', to='traveltime.LargeTown'),
        ),
    ]
