# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traveltime', '0012_auto_20161119_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedDistanceQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=255)),
                ('end', models.CharField(max_length=255)),
                ('time', models.IntegerField()),
            ],
        ),
    ]
